name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t asia-south1-docker.pkg.dev/smarttriage-aiops/smart-triage-repo/smarttriage:latest .

      - name: Push Docker Image
        run: docker push asia-south1-docker.pkg.dev/smarttriage-aiops/smart-triage-repo/smarttriage:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy smarttriage-aiops --image asia-south1-docker.pkg.dev/smarttriage-aiops/smart-triage-repo/smarttriage:latest --region asia-south1 --port 8080 --allow-unauthenticated --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}",GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}",DISCORD_WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
